// examples/with-vue3-vite/src/views/PtzDemo.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref } from 'vue'
import { Ptz } from '@ezuikit/control-ptz'

const containerRef = ref<HTMLElement>()
let ptz: Ptz | null = null

onMounted(() => {
  if (containerRef.value) {
    ptz = new Ptz(containerRef.value, {
      language: 'zh',
      accessToken: 'your-access-token',
      deviceSerial: 'your-device-serial',
      channelNo: 1,
      onDirection: (info) => {
        console.log('Ptz direction:', info)
        return () => {}
      },
      onSpeedChange: (speed) => {
        console.log('Ptz speed:', speed)
      },
    })
  }
})

onUnmounted(() => {
  ptz?.destroy()
})
</script>

<template>
  <div>
    <h2>Ptz 云台控制</h2>
    <div ref="containerRef" style="width: 300px; height: 300px;"></div>
  </div>
</template>

// examples/with-react-vite/src/pages/PtzDemo.tsx
import React, { useEffect, useRef } from "react";
import { Ptz } from "@ezuikit/control-ptz";

export default function PtzDemo() {
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    let ptz: Ptz | null = null;

    if (containerRef.current) {
      ptz = new Ptz(containerRef.current, {
        language: "zh",
        accessToken: "your-access-token",
        deviceSerial: "your-device-serial",
        channelNo: 1,
        onDirection: (info) => {
          console.log("Ptz direction:", info);
          return () => {};
        },
        onSpeedChange: (speed) => {
          console.log("Ptz speed:", speed);
        },
      });
    }

    return () => {
      ptz?.destroy();
    };
  }, []);

  return (
    <div>
      <h2>Ptz 云台控制</h2>
      <div ref={containerRef} style={{ width: 300, height: 300 }} />
    </div>
  );
}
